; empty config to fix `spicetify apply` error ouput

[wal]
main_fg              = ${xrdb:color7}
secondary_fg         = ${xrdb:color7}
main_bg              = ${xrdb:color0}
sidebar_fg           = ${xrdb:color7}
sidebar_bg           = ${xrdb:color0}
cover_bg             = ${xrdb:color0}
indicator_fg         = ${xrdb:color2}
indicator_bg         = ${xrdb:color1}
selected_row_bg      = ${xrdb:color1}
player_bg            = ${xrdb:color0}
button_bg            = ${xrdb:color1}
button_fg            = ${xrdb:color7}
button_active_bg     = ${xrdb:color2}
button_disabled_bg   = ${xrdb:color0}
tab_active_bg        = ${xrdb:color2}
tab_active_fg        = ${xrdb:color7}
tab_inactive_bg      = ${xrdb:color0}
tab_inactive_fg      = ${xrdb:color7}
scrollbar_fg         = ${xrdb:color2}
scrollbar_bg         = ${xrdb:color0}
play_button_bg       = ${xrdb:color2}
play_button_fg       = ${xrdb:color7}
progress_fg          = ${xrdb:color2}
progress_bg          = ${xrdb:color0}
progress_bar_bg      = ${xrdb:color0}
progress_bar_fg      = ${xrdb:color2}