# Theme
source = /home/$USER/.cache/wal/colors-hyprland

# Monitors Import 
source = ~/.config/hypr/UserLaptopConfig/monitors.conf

# My Programs Import
source = ~/.config/hypr/UserLaptopConfig/myprograms.conf

# KeyBinds Import
source = ~/.config/hypr/UserLaptopConfig/binds.conf

# AutoStart Import
source = ~/.config/hypr/UserLaptopConfig/autostart.conf

# Enviroment Variables Import
source = ~/.config/hypr/UserLaptopConfig/env.conf

# Permissions Import
source = ~/.config/hypr/UserLaptopConfig/permissions.conf

# Look And Feel Import
source = ~/.config/hypr/UserLaptopConfig/lookandfeel.conf

# Inputs Import
source = ~/.config/hypr/UserLaptopConfig/inputs.conf

# Windows And Workspaces Import
source = ~/.config/hypr/UserLaptopConfig/windowsandworkspaces.conf

