#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
  kb_layout = us
  follow_mouse = 1
  sensitivity = 1
  touchpad {
    natural_scroll = true
    scroll_factor = 0.5
    tap-to-click = yes
  }
}

# https://wiki.hypr.land/Configuring/Variables/b#gesturesi
gesture = 3, horizontal, workspace

device {
  name = epic-mouse-v1
  sensitivity = -0.5
}
