
##############################
### WINDOWS AND WORKSPACES ###
##############################

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev = suppressevent maximize, class:.* 

# Fix some dragging issues with XWayland
windowrulev = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrulev = float, center, class:^(imv)$

windowrulev = fullscreen,class:^(Battle.net)$
windowrulev = fullscreen,class:^(World of Warcraft)$

windowrulev = fullscreen, class:(Waydroid)

windowrulev = noborder, class:(Waydroid)
windowrulev = noanim, class:(Waydroid)

layerrulev = blur, waybar
layerrulev = ignorezero, waybar
layerrulev = ignorealpha 0.5, waybar
layerrulev = blur, swaync-control-center
layerrulev = blur, swaync-notification-window
layerrulev = ignorezero, swaync-control-center
layerrulev = ignorezero, swaync-notification-window
layerrulev = ignorealpha 0.5, swaync-control-center
layerrulev = ignorealpha 0.5, swaync-notification-window
layerrulev = noanim, selection

windowrulev = float, class:^(kitty-dropterm)$
windowrulev = float, class:^(kitty-pulsemixer)$
windowrulev = float, class:^(kitty-taskbar)$
